version: 1
accounts:
  - name: alice
    coins: ["500000000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  app_state:
    funding:
      params:
        validTokens: "[\"stake\"]"
    mint:
      params:
        mint_denom: "uvst"
        inflation_min: "0.0"
        inflation_rate_change: "0.0"
        inflation_max: "0.0"
